import math
import time
import random
import webbrowser


def supa_hot_fire():
    print("Awesome choice!!!")
    time.sleep(2)
    print("You got around 200 people on your side")
    time.sleep(4)
    print("SPH- first of all Im not a rapper!")
    time.sleep(3)
    supa_hot_fire = "file:///Users/SMHS/Desktop/Screen%20Shot%202017-10-24%20at%209.23.35%20AM.png"
    webbrowser.open(supa_hot_fire)
    SRoast = int(input("Which roast do you want to start with 1.(Your exs' number) , 2.(Sweet dollar tea from McD's) or 3.(leather jacket)"))
    if SRoast == 1:
        print("SPH- Check me out")
        time.sleep(2)
        print("SPH- I broke up with my ex-girl...")
        time.sleep(3)
        print("SPH- here's her numba...")
        time.sleep(2)
        print("SPH- SIKE THATS THE WRONG NUMBA!!!")
        time.sleep(2)
        print("'CROWD GOES CRAZY!!!'")
        time.sleep(3)
        print("Kealoha - What? thats not even a roast!?!")
        time.sleep(2)
        Sroast = int(input("Next roast 1.(Sweet dollar tea from McD's) or 2.(leather jacket)"))
        if Sroast == 1:
            print("SPH- Sweet dolla tea from McDonalds...")
            time.sleep(2)
            print("SPH- I drink that!!!")
            time.sleep(2)
            print("SPH- SUPER HOT FIRE...")
            time.sleep(2)
            print("SPH- I spit that!!!")
            time.sleep(2)
            print("SPH- 2 and a half man...")
            time.sleep(2)
            print("SPH- I WATCH THAT!")
            time.sleep(1)
            print("'CROWD LOSSES CONTROl!!!'")
            sr = int(input("Do you want to 1.(Roast your opponent with leather jacket) 2.(Stop roasting your opponent give him a chance to roast you)"))
            if sr == 1:
                print("SPH: Aight check me out")
                time.sleep(1)
                print("SPH- Glasses, jacket, shirt")
                time.sleep(2)
                print("SPH- call me glasses, jacket shirt-man")
                time.sleep(2)
                print("SPH- Or call me Supa Hot Boy, hundred degrees, leather jacket")
                time.sleep(2)
                print("SPH- Cause Im Supa Hot Boy!(I'm not a rapper)")
                print("Crowd goes crazy")
                H= int(input("Do you want to 1. (give your opponent a chance.) 2.(Hit your opponent with your ultimate roast) "))
                if H == 1:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(1)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(1)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(1)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(1)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(1)
                    print("Kealoha- They told me I had battle, I was like this is who they set up")
                    time.sleep(1)
                    print("Awkward silence")
                    end= int(input("do you want to 1.(hit him with your ultimate roast) 2.(End roast battle)"))
                    if end == 1:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(2)
                        print("everybody dies")
                    else:
                        print("You lost because you ended the roast battle")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("SPH-everybody dies")
            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(2)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(2)
                print("Kealoha- King of the internet, I been that")
                time.sleep(2)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(2)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(2)
                print("Kealoha- They told me I had battle, I was like this is who they set up")
                time.sleep(2)
                print("Awkward silence")
                back = int(input("What do you want to do now. 1. (Roast him with the leather jacket) 2. (Hit him with your ultimate roast)"))
                if back == 1:
                    print("SPH: Aight check me out")
                    time.sleep(2)
                    print("SPH- Glasses, jacket, shirt")
                    time.sleep(2)
                    print("SPH- call me glasses, jacket shirt-man")
                    time.sleep(2)
                    print("SPH- Or call me Supa Hot Boy, hundred degrees, leather jacket")
                    time.sleep(2)
                    print("SPH- Cause Im Supa Hot Boy!(I'm not a rapper)")
                    print("Crowd goes crazy")
                    end = int(input("do you want to 1.(hit him with your ultimate roast) 2.(End roast battle)"))
                    if end == 1:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(1)
                        print("everybody dies")
                    else:
                        print("You lost because you ended the roast battle")

                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("everybody dies")
        else:
            print("SPH- Aight check me out")
            time.sleep(2)
            print("SPH- Glasses, jacket, shirt")
            time.sleep(2)
            print("SPH- call me glasses, jacket shirt-man")
            time.sleep(2)
            print("SPH- Or call me Supa Hot Boy, hundred degrees, leather jacket")
            time.sleep(2)
            print("SPH- Cause Im Supa Hot Boy!(I'm not a rapper!)")
            time.sleep(1)
            print("Crowd goes crazy")
            srosat= int(input("Do you want to 1.(Roast your opponent with sweet dolla tea from McDonalds) 2.(Stop roasting your opponent give him a chance to roast you)"))
            if srosat == 1:
                print("SPH- Sweet dolla tea from McDonalds...")
                time.sleep(2)
                print("SPH- I drink that!!!")
                time.sleep(2)
                print("SPH- SUPER HOT FIRE...")
                time.sleep(2)
                print("SPH- I spit that!!!")
                time.sleep(2)
                print("SPH- 2 and a half man...")
                time.sleep(2)
                print("SPH- I WATCH THAT!")
                time.sleep(1)
                print("'CROWD LOSSES CONTROl!!!'")
                time.sleep(1)
                roast= int(input("Now do you want to 1.(roast him with your ultimate roast) 2.(let him roast you)"))
                if roast == 1:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("everybody dies")
                else:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(2)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(2)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(2)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(2)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(2)
                    print("Kealoha- They told me I had battle, I was like this is who they set up")
                    time.sleep(2)
                    print("Awkward silence")
                    time.sleep(1)
                    roast= int(input("Now do you want to 1.(end battle) 2.(roast him with your ultimate)"))
                    if roast == 1:
                        print("You lost because you ended the roast battle")

                    else:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(1)
                        print("everybody dies")


            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(2)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(2)
                print("Kealoha- King of the internet, I been that")
                time.sleep(2)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(2)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(2)
                print("Kealoha- They told me I had battle, I was like this is who they set up")
                time.sleep(2)
                print("Awkward silence")
                roast= int(input("do you want to 1.(end battle) 2.(hit him with your ultimate roast)"))
                if roast == 1:
                    print("You lost because you ended the roast battle")

                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("everybody dies")



    elif SRoast == 2:
        print("Sweet dolla tea from McDonalds...")
        time.sleep(2)
        print("I drink that!!!")
        time.sleep(2)
        print("SUPER HOT FIRE...")
        time.sleep(2)
        print("I spit that!!!")
        time.sleep(2)
        print("2 and a half man...")
        time.sleep(2)
        print("I WATCH THAT!")
        time.sleep(1)
        print("'CROWD LOSSES CONTROl!!!'")
        time.sleep(2)
        print("Kealoha- What the heck is this?")
        time.sleep(1)
        Sroast = int(input("Next roast 1.(My ex's number) or 2.(leather jacket)"))
        if Sroast == 1:
            print("SPH- Check me out")
            time.sleep(2)
            print("SPH- I broke up with my ex-girl...")
            time.sleep(3)
            print("SPH- here's her numba...")
            time.sleep(2)
            print("SPH- SIKE THATS THE WRONG NUMBA!!!")
            time.sleep(2)
            print("'CROWD GOES CRAZY!!!'")
            time.sleep(3)
            print("Kealoha - What? thats not even a roast!?!")
            time.sleep(2)
            end2 =  int(input("Do you want to 1.(roast your opponent with leather jacket) 2.(let your opponent roast you)"))
            if end2 == 1:
                print("SPH- Aight check me out")
                time.sleep(2)
                print("SPH- Glasses, jacket, shirt")
                time.sleep(2)
                print("SPH- call me glasses, jacket shirt-man")
                time.sleep(2)
                print("SPH- Or call me Supa Hot Boy, hundred degrees, leather jacket")
                time.sleep(2)
                print("SPH- Cause Im Supa Hot Boy!(I'm not a rapper!)")
                time.sleep(1)
                print("Crowd goes crazy")
                time.sleep(1)
                now = int(input("do you want to 1.(let your opponent roast you) 2.(hit him with your ultimate)"))
                if now == 1:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(2)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(2)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(2)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(2)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(2)
                    print("Kealoha- They told me I had battle, I was like this is who they set up")
                    time.sleep(2)
                    print("Awkward silence")
                    end3 = int(input("Do you want to 1.(end battle) 2.(hit him with with your ultimate)"))
                    if end3 == 1:
                        print("You loose becasue you exited the battle")
                    else:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(1)
                        print("everybody dies")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("everybody dies")

            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(2)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(2)
                print("Kealoha- King of the internet, I been that")
                time.sleep(2)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(2)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(2)
                print("Kealoha- They told me I had to battle, I was like this is who they set up")
                time.sleep(2)
                print("Awkward silence")
                end3 = int(input("Do you want to 1.(end battle) 2.(hit him with with your ultimate)"))
                if end3 == 1:
                    print("You loose becasue you exited the battle")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(1)
                    print("everybody dies")


        else:
            print("Aight check me out")
            time.sleep(2)
            print("Glasses, jacket, shirt")
            time.sleep(2)
            print("call me glasses, jacket shirt-man")
            time.sleep(2)
            print("Or call me Supa Hot Boy, hundred degrees, leather jacket")
            time.sleep(2)
            print("Cause Im Supa Hot Boy!(I'm not a rapper)")
            print("Crowd goes crazy")
            time.sleep(1)
            roast = int(input("do you want to 1.(hit your opponent with your ex's number) 2.(let your opponent roast you)"))
            if roast == 1:
                print("SPH- Check me out")
                time.sleep(2)
                print("SPH- I broke up with my ex-girl...")
                time.sleep(3)
                print("SPH- here's her numba...")
                time.sleep(2)
                print("SPH- SIKE THATS THE WRONG NUMBA!!!")
                time.sleep(2)
                print("'CROWD GOES CRAZY!!!'")
                time.sleep(3)
                print("Kealoha - What? thats not even a roast!?!")
                time.sleep(2)
                end = int(input("Do you want to 1.(let your opponent roast you) 2.(hit him with your ultimate roast)"))
                if end == 1:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(2)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(2)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(2)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(2)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(2)
                    print("Kealoha- They told me I had to battle, I was like this is who they set up")
                    time.sleep(2)
                    print("Awkward silence")
                    end3 = int(input("Do you want to 1.(end battle) 2.(hit him with with your ultimate)"))
                    if end3 == 1:
                        print("You loose becasue you exited the battle")
                    else:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(2)
                        print("everybody dies")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(2)
                    print("everybody dies")

            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(2)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(2)
                print("Kealoha- King of the internet, I been that")
                time.sleep(2)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(2)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(2)
                print("Kealoha- They told me I had to battle, I was like this is who they set up")
                time.sleep(2)
                print("Awkward silence")
                end3 = int(input("Do you want to 1.(end battle) 2.(hit him with with your ultimate)"))
                if end3 == 1:
                    print("You loose becasue you exited the battle")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(2)
                    print("everybody dies")

    else:
        print("Aight check me out")
        time.sleep(2)
        print("Glasses, jacket, shirt")
        time.sleep(2)
        print("call me glasses, jacket shirt-man")
        time.sleep(2)
        print("Or call me Supa Hot Boy, hundred degrees, leather jacket")
        time.sleep(2)
        print("Cause Im Supa Hot Boy!(I'm not a rapper)")
        print("Crowd goes crazy")
        time.sleep(1)
        Sroast = int(input("Next roast 1.(My ex's number) or 2.(Sweet dolla tea from McDonalds)"))
        if Sroast == 1:
            print("SPH- Check me out")
            time.sleep(2)
            print("SPH- I broke up with my ex-girl...")
            time.sleep(3)
            print("SPH- here's her numba...")
            time.sleep(2)
            print("SPH- SIKE THATS THE WRONG NUMBA!!!")
            time.sleep(2)
            print("'CROWD GOES CRAZY!!!'")
            time.sleep(3)
            print("Kealoha - What? thats not even a roast!?!")
            time.sleep(2)
            srosat = int(input("Do you want to 1.(Roast your opponent with sweet dolla tea from McDonalds) 2.(Stop roasting your opponent give him a chance to roast you)"))
            if srosat == 1:
                print("SPH- Sweet dolla tea from McDonalds...")
                time.sleep(2)
                print("SPH- I drink that!!!")
                time.sleep(2)
                print("SPH- SUPER HOT FIRE...")
                time.sleep(2)
                print("SPH- I spit that!!!")
                time.sleep(2)
                print("SPH- 2 and a half man...")
                time.sleep(2)
                print("SPH- I WATCH THAT!")
                time.sleep(1)
                print("'CROWD LOSSES CONTROl!!!'")
                time.sleep(1)
                end = int(input("Do you want to 1. (Let your opponent roast you) 2. (Hit him with your ultimate roast)"))
                if end == 1:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(1)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(1)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(1)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(1)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(1)
                    print("Kealoha- They told me I had battle, I was like this is who they set up")
                    time.sleep(1)
                    print("Awkward silence")
                    end1 = int(input("Do you want to 1. (end roast battle) 2. (hit him with your ultimate roast)"))
                    if end1 == 1:
                        print("You loose because you have to roast back your opponent before exiting the match")

                    else:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(1)
                        print("everybody dies")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(2)
                    print("everybody dies")

            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(1)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(1)
                print("Kealoha- King of the internet, I been that")
                time.sleep(1)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(1)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(1)
                print("Kealoha- They told me I had battle, I was like this is who they set up")
                time.sleep(1)
                print("Awkward silence")
                end3 = int(input("Do you want to 1.(end roast battle) 2.(hit him with your ultimate)"))
                if end3 == 1:
                    print("You loose becasue you exited the battle")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(2)
                    print("everybody dies")
        else:
            print("SPH- Sweet dolla tea from McDonalds...")
            time.sleep(2)
            print("SPH- I drink that!!!")
            time.sleep(2)
            print("SPH- SUPER HOT FIRE...")
            time.sleep(2)
            print("SPH- I spit that!!!")
            time.sleep(2)
            print("SPH- 2 and a half man...")
            time.sleep(2)
            print("SPH- I WATCH THAT!")
            time.sleep(1)
            print("'CROWD LOSSES CONTROl!!!'")
            time.sleep(1)
            srosat = int(input("Do you want to 1.(Roast your opponent with your ex's number) 2.(Stop roasting your opponent give him a chance to roast you)"))
            if srosat == 1:
                print("SPH- Check me out")
                time.sleep(2)
                print("SPH- I broke up with my ex-girl...")
                time.sleep(3)
                print("SPH- here's her numba...")
                time.sleep(2)
                print("SPH- SIKE THATS THE WRONG NUMBA!!!")
                time.sleep(2)
                print("'CROWD GOES CRAZY!!!'")
                time.sleep(3)
                print("Kealoha - What? thats not even a roast!?!")
                time.sleep(2)
                now = int(input("Do you want to 1.(give your opponent a chance of roasting you) 2.(hit him with your ultimate)"))
                if now == 1:
                    print("SPH- Aight Kealoha your turn.")
                    time.sleep(1)
                    print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                    time.sleep(1)
                    print("Kealoha- King of the internet, I been that")
                    time.sleep(1)
                    print("Kealoha- Winning streakes, I end that")
                    time.sleep(1)
                    print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                    time.sleep(1)
                    print("Kealoha- They told me I had battle, I was like this is who they set up")
                    time.sleep(1)
                    print("Awkward silence")
                    end3 = int(input("Do you want to 1.(end roast battle) 2.(hit him with your ultimate)"))
                    if end3 == 1:
                        print("You loose becasue you exited the battle")
                    else:
                        print("SPH- First of all, Im not your friend, so stop lookin' at me")
                        time.sleep(2)
                        print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                        time.sleep(2)
                        print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                        time.sleep(2)
                        print("SPH- look")
                        time.sleep(2)
                        print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                        time.sleep(2)
                        print("everybody dies")
            else:
                print("SPH- Aight Kealoha your turn.")
                time.sleep(1)
                print("Kealoha- Is this who they put me up agaist, SUPA HOT, I never heard of you")
                time.sleep(1)
                print("Kealoha- King of the internet, I been that")
                time.sleep(1)
                print("Kealoha- Winning streakes, I end that")
                time.sleep(1)
                print("Kealoha- I'm like Shaq, I get fouled and then he's back to drop 32 'Shots!'")
                time.sleep(1)
                print("Kealoha- They told me I had battle, I was like this is who they set up")
                time.sleep(1)
                print("Awkward silence")
                end3 = int(input("Do you want to 1.(end roast battle) 2.(hit him with your ultimate)"))
                if end3 == 1:
                    print("You loose becasue you exited the battle")
                else:
                    print("SPH- First of all, Im not your friend, so stop lookin' at me")
                    time.sleep(2)
                    print("SPH- Second of all, I'm not a rapper, so stop rappin' about me")
                    time.sleep(2)
                    print("SPH- I'm bout to end this man's whole career, but I'm not a rapper")
                    time.sleep(2)
                    print("SPH- look")
                    time.sleep(2)
                    print("SPH- Boom, bam, bop, bada bop, boom, POW!")
                    time.sleep(2)
                    print("everybody dies")

def Kealoha():
    print("Uh I really don't know why you chose this character. You got one person on your side...Your homie Shamba")
    time.sleep(3)
    kealoha = "file:///Users/SMHS/Desktop/Screen%20Shot%202017-10-24%20at%209.31.21%20AM.png"
    webbrowser.open(kealoha)
    print("You get roasted to death")
    time.sleep(2)
    print("SPH- By the way none of your students liked you JoJo Kealoha")



def main():
    print("ROAST BATTLE OF THE CENTURY")
    time.sleep(2)
    print("On June 5 of 2013 a brave man named Kealoha with the record of 3-3 is going against the legend, the one and only Supa_Hot_Fire with the record of 398,246,301 wins to 0 losses in a roast battle.")
    time.sleep(3)
    print("Welcome to the most intense minutes of your life.")
    time.sleep(3)
    print("Right now you are getting ready to roast the heck out of your opponent.")
    time.sleep(2)
    Character = int(input("Do you want to be 1.(Kealoha) or 2. (supa_hot_fire)"))
    if Character == 1:
        Kealoha()
    else:
        supa_hot_fire()

main()